### PR TITLE
CColor -> CHyprColor

### PR DESCRIPTION
**Pull request by cpiber**
Introduced by recent move to abstract colors via hyprgraphics

### CODE REVIEW

**Comment by dawsers** [comment]
Thank you.

As usual, I am going to wait to merge this until the 0.46.0 release, probably next week or so, because I am in the middle of some addition I would still want merged for v0.45.2.

**Comment by DeepReef11** [comment]
That fixed it for me. Using hyprland 0.45.0

**Comment by dawsers** [comment]
> That fixed it for me. Using hyprland 0.45.0

In case it is unintended, you are using a git version of Hyprland. The change `Ccolor->CHyprColor` happened after v0.45.2 was released, and hasn't been included in any point release yet.

**Comment by DeepReef11** [comment]
Strange, hyprctl version gives me 0.45.0. And the errors were totally linked to this pr. Could this have something to do with the ml4w configs?

**Comment by dawsers** [comment]
Thank you!

**Pull request merged**
